export const BOOKS_REPOSITORY = 'BOOKS_REPOSITORY';
export const BORROWED_BOOK_REGISTRY = 'BORROWED_BOOK_REGISTRY';
export const ADD_BOOK_TO_CATALOG = 'ADD_BOOK_TO_CATALOG';
export const GET_AVAILABLE_BOOKS = 'GET_AVAILABLE_BOOKS';
