export const MEMBERS_REPOSITORY = 'MEMBERS_REPOSITORY';
export const LOANS_REPOSITORY = 'LOANS_REPOSITORY';
export const BOOK_REFERENCES_REPOSITORY = 'BOOK_REFERENCES_REPOSITORY';
export const BORROW_BOOK = 'BORROW_BOOK';
export const RETURN_BOOK = 'RETURN_BOOK';
export const GET_MEMBER_LOANS = 'GET_MEMBER_LOANS';
